export const CATEGORIES_ACTION_TYPES={
    FETCH_CATEGORIES_START:'category/FETCH_CATEGORIES_START',
    FETCH_CATEGORIES_CUCCESS:'category/FETCH_CATEGORIES_CUCCESS',
    FETCH_CATEGORIES_FAILED:'category/FETCH_CATEGORIES_FAILED',
}
